
### REGISTER
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "username": "annie",
    "email": "annie@mail.com",
    "password": "123"
}

### LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "password"
}

### LOGOUT
POST http://localhost:5000/auth/logout

### ADD INGRIDIENT
POST http://localhost:5000/users_fridge
Content-Type: application/json

### GET INGRIDIENTS
GET http://localhost:5000/users_fridge
Content-Type: application/json
